[code]
editor = 'nvim'
lang = 'python'

[cookies]
csrf = 'EZqEa7tXmcAei3nUTfdx35DplbewvghgAeycAiIxMCabv0cybDEquI253EiKpSnw'
session = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfYXV0aF91c2VyX2lkIjoiMzY3MDIxOSIsIl9hdXRoX3VzZXJfYmFja2VuZCI6ImFsbGF1dGguYWNjb3VudC5hdXRoX2JhY2tlbmRzLkF1dGhlbnRpY2F0aW9uQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6ImExYmNmNTNhMDQzMWE2ZWVkZDA0OGY5YzJjYmZkMmI5MzE4MmIzYjEwM2MyOTgzMmZkM2M0MDNjOGUzODYzYTgiLCJpZCI6MzY3MDIxOSwiZW1haWwiOiJsdWNlcm5hcy5takBnbWFpbC5jb20iLCJ1c2VybmFtZSI6Im1hcmtsY3JucyIsInVzZXJfc2x1ZyI6Im1hcmtsY3JucyIsImF2YXRhciI6Imh0dHBzOi8vYXNzZXRzLmxlZXRjb2RlLmNvbS91c2Vycy9tYXJrbGNybnMvYXZhdGFyXzE2MDc2NzEzNzkucG5nIiwicmVmcmVzaGVkX2F0IjoxNzE0ODAwMTI1LCJpcCI6IjcwLjk1LjEyOS41NiIsImlkZW50aXR5IjoiNDIyZmEzNTMwZjQzZDVkMjIyYmUxY2QwN2JiYTA0OGMiLCJzZXNzaW9uX2lkIjo2MDgzNDY5OX0.g-BcQJLuV3Su7INUkV-p19wE2OFuqguMJHelGA6lG_Q'

[storage]
cache = 'Problems'
code = 'code'
scripts = 'scripts'
root = '~/Sync/dev/leetcode-cli'

