#!/usr/bin/env bash

set -o pipefail
set -o nounset

function _main() {
  local -a _rc_files=(
    "-m git -A 'Mark Lucernas' -d 'my-scripts.git git-lfs' -a '--depth=1' -n my-dotfiles -o '~/.dotfiles' -- https://github.com/marklcrns/.dotfiles"
    "-m git -A 'Mark Lucernas' -d 'yarn python3-venv neovim pandoc' -a '--recurse-submodules --depth=1' -n my-neovim-rc -o '~/.config/nvim' -- https://github.com/marklcrns/nvim-config"
    "-m git -A 'Mark Lucernas' -d 'taskwarrior' -a '--depth=1' -n my-taskwarrior-rc -o '~/.task' -- https://github.com/marklcrns/.task"
    "-m git -A 'Mark Lucernas' -d 'timewarrior' -a '--depth=1' -n my-timewarrior-rc -o '~/.timewarrior' -- https://github.com/marklcrns/.timewarrior"
    "-m git -A 'Mark Lucernas' -d 'tmuxinator' -a '--depth=1' -n my-tmuxinator-rc -o '~/.tmuxinator' -- https://github.com/marklcrns/.tmuxinator"
    "-m git -A 'Mark Lucernas' -a '--depth=1' -n my-secret-rc -o '~/.secret' -- https://github.com/marklcrns/.secret"
  )
  local -a _misc=(
    "-m local -A 'Mark Lucernas' -d 'nix' -c neuron -n neuron neuron"
    "-m git -A 'Mark Lucernas' -d 'git-lfs' -a '--depth=1' -n my-wiki -o '~/Documents/my-wiki' -- https://github.com/marklcrns/my-wiki"
    "-m git -A 'Mark Lucernas' -a '--depth=1' -n my-scripts -o '~/scripts' -- https://github.com/marklcrns/scripts"
  )

  local -a packages=(
    "${_rc_files[@]}"
    "${_misc[@]}"
  )

  for package in "${packages[@]}"; do
    ez gen --skip-confirm --skip-edit --debug ${package}
  done
}

res=0
_main
res=$?

unset DEBUG

exit $res
